name = "getfly-sync"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "getfly-connections"
database_id = "4487b143-3438-4ffb-afe7-dc751996d819"
